sudo: false
language: java
jdk:
  - oraclejdk10
  - oraclejdk9
  - oraclejdk8
cache:
  directories:
    - "$HOME/.m2/repository"
before_cache:
  - rm -rf $HOME/.m2/repository/org/threeten
install:
  - mvn --version
script:
  - mvn install site -e -B
  - if [[ $TRAVIS_TAG =~ ^v.*$ ]] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_JDK_VERSION" == "oraclejdk10" ]; then chmod +x ./.github/website.sh; .github/website.sh; fi
# secure keys for GITHUB_TOKEN
env:
  global:
  - secure: FaC3K5L6pGdJgvPcttpq8kV5i+UUsj5FWvETqm82BZWzLTYlQsCL4fl2XfssATiH7hIVioRffYoZP8rQbkNatVV+Pok6wZePSM9kOf7/AUOn0dvwXH718sbWlohOf3R3886/l5rjyJDDmauMABXzLrXxsTlbiQ85QNA0mCbqXJ4=
